name: Build macOS App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  mac-build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with: { python-version: '3.x' }

      - name: Install deps
        run: |
          pip install --upgrade pip
          pip install customtkinter pyinstaller

      - name: Build .app with PyInstaller
        run: |
          pyinstaller --windowed --name "Niagara Lesson Builder" main.py
          # or:  pyinstaller niagara.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: NiagaraLessonBuilder-macOS
          path: dist/Niagara\ Lesson\ Builder.app
